site_name: Dreamer's Wiki
site_description: 'Another Cyber Security Wiki'
site_url: https://ismailbozkurt.github.io/Dreamer-Wiki/

repo_url: https://github.com/ismailbozkurt/Dreamer-Wiki/
edit_uri: blob/main/docs/
theme:
  name: material
  extra_css:
  - override/override.css
  custom_dir: overrides
  color_mode: auto
  user_color_mode_toggle: true
  features:
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
  - scheme: default
    toggle:
      icon: material/toggle-switch-off-outline 
      name: Switch to dark mode
    primary: black
    accent: purple 
  - scheme: slate 
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode    
    primary: black       # 🟢 <- This changes the green header
    accent: lime


plugins:
  - social
  - search

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/ismailbozkurt
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/ismail-bozkurtr/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2025 <a href="https://github.com/ismailbozkurt"  target="_blank" rel="noopener">İsmail BOZKURT</a>